### PR TITLE
Solution lyrics finder #WIP

### PR DESCRIPTION
**Pull request by bhk31**
1. Created UI for search.
2. Fetched searched result.
3. Displayed the list of search.

### CODE REVIEW

**Review by ArfatSalman — COMMENTED** [review]
> Created UI for search.

Where is it?

**Comment by bhk31** [comment]
Created UI for search. in index.html
Fetched searched result. on click of search button  
Displayed the list of search.

**Comment by ArfatSalman** [comment]
@bhk31 I still can't see your mock screens. Do you want to put them? 

In any case, you can continue working on your project.

**Comment by bhk31** [comment]
> @bhk31 I still can't see your mock screens. Do you want to put them?
> 
> In any case, you can continue working on your project.




These are the screens which I have completed currently.

Thinking of adding some image on landing screen and logo. 
Also there will be next and previous button below search result.

Let me know your thoughts on it.

**Comment by ArfatSalman** [comment]
The home screen looks very empty on the first load. Why not populate it with something default?

**Comment by bhk31** [comment]
Updated home page to show default artist list.
Added logo for the site.
Added code to list songs of artist after clicking on artist.
Removed background color.

Before 



After 


To view current build Please visit [here ](https://pesto-students.github.io/lyrics-finder-bhk31/)

**Comment by ArfatSalman** [comment]
Looks much better. Good work! Start implementing this!

**Pull request merged**
